DROP TABLE assisstant CASCADE;
DROP SEQUENCE assisstant_oid_seq CASCADE;
DROP TABLE building(location or place) CASCADE;
DROP SEQUENCE building(location or place)_oid_seq CASCADE;
DROP TABLE department CASCADE;
DROP SEQUENCE department_oid_seq CASCADE;
DROP TABLE dependent of employee CASCADE;
DROP SEQUENCE dependent of employee_oid_seq CASCADE;
DROP TABLE employee CASCADE;
DROP SEQUENCE employee_oid_seq CASCADE;
DROP TABLE employee_has_dependent of employee CASCADE;
DROP TABLE engineer CASCADE;
DROP SEQUENCE engineer_oid_seq CASCADE;
DROP TABLE office CASCADE;
DROP SEQUENCE office_oid_seq CASCADE;
DROP TABLE project CASCADE;
DROP SEQUENCE project_oid_seq CASCADE;
DROP TABLE project area CASCADE;
DROP SEQUENCE project area_oid_seq CASCADE;
DROP TABLE project_work in_employee CASCADE;
DROP TABLE researcher CASCADE;
DROP SEQUENCE researcher_oid_seq CASCADE;
DROP TABLE survey plan CASCADE;
DROP SEQUENCE survey plan_oid_seq CASCADE;
DROP TABLE technician CASCADE;
DROP SEQUENCE technician_oid_seq CASCADE;
DROP TABLE codelist_contract type CASCADE;
DROP SEQUENCE codelist_contract type_oid_seq CASCADE;
DROP TABLE codelist_type of employee CASCADE;
DROP SEQUENCE codelist_type of employee_oid_seq CASCADE;
DROP TABLE codelist_type of investment opportunities CASCADE;
DROP SEQUENCE codelist_type of investment opportunities_oid_seq CASCADE;
DROP TABLE codelist_type of marketing CASCADE;
DROP SEQUENCE codelist_type of marketing_oid_seq CASCADE;
